datosgobar/portal-base

- base_portal/group_vars/all.yml
- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/tasks/install_ckan.yml
- base_portal/roles/portal/templates/scripts/config/run_updates.sh.j2
- base_portal/roles/portal/templates/scripts/config/updates/0001_fix_emails.sh.j2
- base_portal/roles/portal/templates/scripts/config/updates/README
- deploy/update.py
Agrego scripts de update de configuración.
> Agrego scripts de update

- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/templates/scripts/config/build-combined-ckan-mo.sh
El script build-combined-ckan-mo.sh va a "mergear" las traducciones que vienen con ckan con las que se agreguen en cada portal.
> Script para agregar traducciones

- base_portal/roles/portal/files/recline/recline.js
https://github.com/datosgobar/portal-andino-theme/issues/63
> Agrego traducciones del data-previewer

- base_portal/roles/portal/tasks/install_ckan.yml
> 36 disponibilizar requirements de ckanext harvest

- base_portal/roles/portal/templates/scripts/start_ckan.sh.j2
Gracias @z017 y @JoseSalgado1024
closes #34
> Fuerzo que se elimine el pidfile con logging

- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/templates/apache/ckan_default.conf.j2
- base_portal/roles/portal/templates/apache/datapusher.conf.j2
Los logs de apache va a consola.
Closes #21
> Configuro los logs de de apache para que salgan por consola

- base_portal/roles/portal/templates/scripts/config/add_admin.sh.j2
- docs/imagenes/base_portal.md
Documento el parámetro adicional
> Agrego validación de que el mail del admin sea pasado al crear el admin

- base_portal/Dockerfile
Agrego el timezone default a Argentina
Ver tambien https://github.com/datosgobar/portal-andino/pull/147
> Agrego el timezone default

- base_portal/roles/portal/templates/ckan/production.ini.j2
refs datosgobar/portal-andino-theme#346
> Agrego plugin ckanext-dcat

- nginx/command.sh
> La creación del archivo de DH params se realiza una sola vez

- base_portal/group_vars/all.yml
- base_portal/roles/portal/tasks/install_ckan.yml
> Utilizamos la versión 0.12 de Flask para evitar errores con datapusher

- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/templates/scripts/config/updates/0005_add_series_api_uri_default_value.sh.j2
> Agregar una uri default para el explorador de series en caso de que no se haya hecho

- nginx/command.sh
- nginx/configs/nginx_ssl.conf
Mergear antes que datosgobar/portal-andino#180.
> Redirección correcta de HTTP a HTTPS

- nginx/command.sh
- nginx/configs/nginx.conf
- nginx/configs/nginx_ssl.conf
Ver datosgobar/portal-andino#196
> Soporte para la parametrización del tamaño máximo de archivos

- base_portal/roles/portal/tasks/configure.yml
Ver https://github.com/datosgobar/portal-andino/issues/225.
> Traigo la migración de licencias

- deploy/update.py
Mediante subprocess:
* busco las tareas croneadas y las guardo en una variable
* en caso de existir tareas, se las guarda de nuevo luego de actualizar la aplicación
Ver datosgobar/portal-andino#226
> Actualizo update.py para deploys

- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/templates/scripts/config/updates/0009_make_sure_who_security_file_exists.sh.j2
* Si existe, no hago nada
* Si no existe:
* Si existe el template, lo muevo al path correspondiente
* Si no existe, lo descargo de Github
> Agrego migración para asegurarse de que exista who_security.ini

- base_portal/roles/portal/templates/scripts/datastore_loaders/enable_ckanext_xloader.sh.j2
Relacionado a https://github.com/datosgobar/portal-andino-theme/pull/445.
> Elimino pip installs para pasarlos a portal-andino-theme

- base_portal/roles/portal/tasks/configure.yml
- base_portal/roles/portal/templates/scripts/config/updates/0010_update_comment_in_datastore_cronjob.sh.j2
- base_portal/roles/portal/templates/scripts/datastore_loaders/enable_ckanext_xloader.sh.j2
- base_portal/roles/portal/templates/scripts/datastore_loaders/enable_datapusher.sh.j2
Actualizo scripts de croneo de subida a datastore + creo migración para que la estrategia funcione
> Adapto la estrategia de croneo de tareas a la existencia del xloader

- base_portal/roles/portal/templates/scripts/config/init.sh
Closes datosgobar/portal-andino#253
Agrega manejo para usuarios con caracteres en mayúsculas
> 253 bugfix instalacion psql

- base_portal/roles/portal/templates/ckan/production.ini.j2
- base_portal/roles/portal/templates/scripts/config/updates/0004_add_dcat_and_structured_data_config.sh.j2
> Agrego sed para agregar la configuración de dcat en el config file en migración para el plugin

- base_portal/roles/portal/templates/ckan/units.json.j2
> Fix archivo unidades
